services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: parkrun
      POSTGRES_PASSWORD: parkrun
      POSTGRES_DB: parkrun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkrun"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - ./data:/app/data
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - FRONTEND_URL=http://localhost:5173
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - api

volumes:
  postgres_data: