services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: parkrun
      POSTGRES_PASSWORD: parkrun
      POSTGRES_DB: parkrun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkrun"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://parkrun:parkrun@postgres:5432/parkrun?schema=public
      NODE_ENV: development
      PORT: 3001
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
      - /app/prisma/node_modules
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data: