services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: parkrun
      POSTGRES_PASSWORD: parkrun
      POSTGRES_DB: parkrun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: