FROM node:22-slim

WORKDIR /app

RUN apt-get update && apt-get install -y openssl
COPY package*.json ./
RUN npm install

# Copy Prisma schema and generate client
COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

CMD ["npm", "run", "dev:api"]