FROM node:23-slim

WORKDIR /app

RUN apt-get update && apt-get install -y openssl
COPY package*.json ./
RUN npm install
RUN npm install -g tsx

COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

CMD ["npm", "run", "api"]