-- Create readonly role for Data API access
CREATE ROLE readonly WITH LOGIN;
GRANT CONNECT ON DATABASE parkrun TO readonly;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;

-- Create admin role for management
CREATE ROLE admin WITH LOGIN CREATEDB CREATEROLE;
GRANT ALL PRIVILEGES ON DATABASE parkrun TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO admin;

-- Enable IAM authentication for these roles
ALTER ROLE readonly WITH LOGIN PASSWORD 'dummy_password' IAM AUTHENTICATION;
ALTER ROLE admin WITH LOGIN PASSWORD 'dummy_password' IAM AUTHENTICATION;
