Parameters:
  GitHubOrg:
    Type: String
  RepositoryName:
    Type: String

Resources:
  GithubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - "6938fd4d98bab03faadb97b34396831e3780aea1"

  GithubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubActionsRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidcProvider
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: StaticSiteDeploymentPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # CDK deployment permissions
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - cloudfront:*
                  - logs:*
                  - iam:*
                Resource: "*"

              # Route53 permissions for domain management
              - Effect: Allow
                Action:
                  - route53:GetHostedZone
                  - route53:ListHostedZones
                  - route53:GetHostedZoneCount
                  - route53:ChangeResourceRecordSets
                  - route53:ListResourceRecordSets
                Resource: 
                  - !Sub "arn:aws:route53:::hostedzone/*"
              
              # ACM permissions for certificate
              - Effect: Allow
                Action:
                  - acm:RequestCertificate
                  - acm:DescribeCertificate
                  - acm:DeleteCertificate
                  - acm:ListCertificates
                  - acm:AddTagsToCertificate
                Resource: "*"
              - Effect: Allow
                Action:
                  - acm:RequestCertificate
                  - acm:DescribeCertificate
                Resource: !Sub "arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/*"

              # S3 permissions
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - "arn:aws:s3:::*"
                  - "arn:aws:s3:::*/*"
              
              # SSM permissions for CDK bootstrap
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                  - ssm:DeleteParameter
                Resource: 
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cdk-bootstrap/*
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cdk/*

              # Lambda and API Gateway permissions
              - Effect: Allow
                Action:
                  - lambda:*
                  - apigateway:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - lambda:UpdateFunctionCode
                Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:parkrun-api-*

Outputs:
  RoleArn:
    Description: ARN of the GitHub Actions Role
    Value: !GetAtt GithubActionsRole.Arn
