name: Deploy Frontend

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    types:
      - completed
    branches: [main]
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
      - '!**.md'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          
      - name: Install Dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build Frontend
        env:
          TARGET_ENV: ${{ github.event.inputs.environment || 'dev' }}
        run: |
          cd frontend
          npm run build
            
      - name: Deploy Frontend and invalidate CloudFront
        env:
          TARGET_ENV: ${{ github.event.inputs.environment || 'dev' }}
        run: |
          aws s3 sync frontend/dist s3://${{ secrets[format('FRONTEND_BUCKET_{0}', env.TARGET_ENV)] }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets[format('CLOUDFRONT_ID_{0}', env.TARGET_ENV)] }} --paths "/*"