name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'cdk/**'
      - '.github/workflows/deploy-infra.yml'
      - '!**.md'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          
      - name: Install CDK Dependencies
        run: |
          cd cdk
          npm ci
          
      - name: Deploy Infrastructure
        run: |
          cd cdk
          npm run deploy -- --require-approval never
