name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'cdk/**'
      - '.github/workflows/deploy-infra.yml'
      - '!**.md'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          
      - name: Install CDK Dependencies
        run: |
          cd cdk
          npm ci
          
      - name: Deploy Infrastructure
        id: deploy
        run: |
          cd cdk
          # Deploy and save outputs
          npm run deploy -- --require-approval never --outputs-file outputs.json
          
          # Debug outputs file
          echo "Contents of outputs.json:"
          cat outputs.json
          
          # Extract values using proper stack name
          STACK_NAME="ParkRunStack" # Adjust this to match your actual stack name
          BUCKET_NAME=$(jq -r ".[\"$STACK_NAME\"].BucketName" outputs.json)
          DISTRIBUTION_ID=$(jq -r ".[\"$STACK_NAME\"].DistributionId" outputs.json)
          
          # Debug extracted values
          echo "Extracted Bucket Name: $BUCKET_NAME"
          echo "Extracted Distribution ID: $DISTRIBUTION_ID"
          
          # Set outputs
          echo "bucket_name=${BUCKET_NAME}" >> $GITHUB_OUTPUT
          echo "distribution_id=${DISTRIBUTION_ID}" >> $GITHUB_OUTPUT
  
      - name: Update GitHub Secrets
        uses: gliech/create-github-secret-action@v1
        with:
          name: FRONTEND_BUCKET
          value: ${{ steps.deploy.outputs.bucket_name }}
          pa_token: ${{ secrets.GH_PA_TOKEN }}
            
      - name: Update Distribution ID
        uses: gliech/create-github-secret-action@v1
        with:
          name: CLOUDFRONT_ID
          value: ${{ steps.deploy.outputs.distribution_id }}
          pa_token: ${{ secrets.GH_PA_TOKEN }}
