name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
      runs-on: ubuntu-latest
      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
      
      steps:
        - uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'
            
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: eu-central-1
            
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2
            
        - name: Build and Push Lambda Container
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.LAMBDA_ECR_REPOSITORY }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            cd backend
            docker build -f Dockerfile.api -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            
        - name: Update Lambda Function
          run: |
            aws lambda update-function-code \
              --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
              --image-uri ${{ steps.login-ecr.outputs.registry }}/${{ secrets.LAMBDA_ECR_REPOSITORY }}:${{ github.sha }}